#!/bin/bash

docker network create my-network || true

docker rm -f elasticsearch

docker run -p 9200:9200 -d --name elasticsearch --network my-network \
-e "discovery.type=single-node" \
-e "xpack.security.enabled=false" \
-e "xpack.ml.use_auto_machine_memory_percent=true" \
-e "xpack.license.self_generated.type=trial" \
-v "elasticsearch-data:/usr/share/elasticsearch/data" \
docker.elastic.co/elasticsearch/elasticsearch:8.15.2

